### ISSUE TITLE
Update README to explain parameters

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/lsif-cpp#4] opened 2019-11-17 18:36 UTC
While going through setting up this LSIF indexer on a C project, there were a few things that weren't clear:
- What does ABSROOTDIR and ABSOUTDIR represent? What are they used for and where should they point to?
- When running lsif-cpp, it assumes that the C compiler used is linked to the LLVM. For this particular setup, they were not, so it would be nice to be able to pass this information
- Similarly for the conversion of the CSV files to LSIF, what are the parameters supposed to be pointing at? 

We were able to work through and successfully generate an LSIF file, but when uploading it, we encountered two different errors on try 1 and try 2:
1. 404 Not Found Unknown commit.
1. stream error: stream ID 1; INTERNAL_ERROR

Not sure if this is an error with the uploader, or with the LSIF indexer.

**Comment by chrismwendt** [comment] 2019-11-18 20:49
Thanks for running through this 🙇 

Updated docs in https://github.com/sourcegraph/lsif-cpp/commit/5c9ab4ec1f38b86d9562fa7057431ff82da7e9a2

I'm not sure what happened with the "Unknown commit" error. The next time this happens, it would be helpful to see the full stdout of the upload command, the output of `git rev-parse HEAD`, etc.

The cause of "stream error" was fixed in ~~https://github.com/sourcegraph/sourcegraph/pull/6622~~ https://github.com/sourcegraph/sourcegraph/pull/6648.

**Closed as completed by chrismwendt** 2019-11-18 20:49 UTC
